# Generated by Django 4.2.5 on 2023-10-01 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_resources', '0002_alter_hospital_nombre_alter_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_reporte', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_entrada', models.TimeField()),
                ('salida', models.CharField(max_length=256)),
                ('entrada', models.CharField(max_length=256)),
                ('observaciones', models.TextField()),
                ('personal', models.CharField(max_length=256)),
                ('radiotelefonista', models.CharField(max_length=256)),
                ('pilotos', models.TextField()),
                ('unidades', models.TextField()),
                ('personal_destacado', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=256)),
                ('solicitantes', models.TextField()),
                ('pacientes', models.TextField()),
                ('fallecidos', models.TextField()),
                ('acompaniantes', models.TextField()),
                ('domicilios', models.TextField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='module_resources.hospital')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='module_resources.servicio')),
            ],
        ),
    ]
