# Generated by Django 4.2.5 on 2023-10-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_resources', '0002_alter_hospital_nombre_alter_servicio_nombre_and_more'),
        ('module_reports', '0002_remove_reporte_unidades_reporte_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='control',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='acompaniantes',
            field=models.TextField(verbose_name='Acompañantes'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='entrada',
            field=models.CharField(max_length=256, verbose_name='Entrada a'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_reporte',
            field=models.DateField(verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora_entrada',
            field=models.TimeField(verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora_salida',
            field=models.TimeField(verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='pilotos',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='salida',
            field=models.CharField(max_length=256, verbose_name='Salida a'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='unidades',
            field=models.ManyToManyField(to='module_resources.vehiculo', verbose_name='Unidad(es)'),
        ),
    ]
