# Generated by Django 4.2.5 on 2023-10-02 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_reports', '0003_remove_reporte_control_alter_reporte_acompaniantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_atendiente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='pilotos',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='radiotelefonista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telefonista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='pilotos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Piloto(s)'),
        ),
    ]
