# Generated by Django 4.2.5 on 2023-10-08 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_resources', '0002_alter_hospital_nombre_alter_servicio_nombre_and_more'),
        ('module_reports', '0004_alter_reporte_personal_remove_reporte_pilotos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='acompaniantes',
            new_name='escoltas',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='telefono',
        ),
        migrations.AddField(
            model_name='reporte',
            name='control',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_solicitud',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('personal', 'Personal')], default=1, max_length=10, verbose_name='Tipo de solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(max_length=256, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fallecidos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora_entrada',
            field=models.DateTimeField(verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='hora_salida',
            field=models.DateTimeField(verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='pacientes',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='personal_destacado',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='module_resources.servicio', verbose_name='Tipo de servicio'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='personal_destacado',
            field=models.ManyToManyField(related_name='personal', to=settings.AUTH_USER_MODEL, verbose_name='Personal Destacado'),
        ),
    ]
