# Generated by Django 4.2.5 on 2023-10-28 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_reports', '0006_alter_reporte_escoltas_alter_reporte_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='formalizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='formalizador', to=settings.AUTH_USER_MODEL, verbose_name='Formalizador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='jefe_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jefe_de_servicio', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Servicio'),
            preserve_default=False,
        ),
    ]
